"""
Handoff document generation tools for Donna.

Creates context documents when ideating on specific projects,
allowing seamless transition from Donna to project workspaces.

All data stored in Supabase - NO local file access.
"""

import json
import re
import logging
from typing import Optional
from datetime import datetime
from uuid import uuid4

from langchain_core.tools import tool
from langchain_openai import ChatOpenAI

from donna.config import get_settings
from donna.database import get_supabase_client

logger = logging.getLogger(__name__)


def get_project_from_supabase(project_name: str) -> Optional[dict]:
    """Get project from Supabase by name or ID."""
    try:
        supabase = get_supabase_client()
        if not supabase:
            return None
        
        # Try exact match on name
        result = supabase.table("projects").select("*").ilike(
            "name", project_name
        ).limit(1).execute()
        
        if result.data:
            return result.data[0]
        
        # Try partial match
        result = supabase.table("projects").select("*").ilike(
            "name", f"%{project_name}%"
        ).limit(1).execute()
        
        return result.data[0] if result.data else None
        
    except Exception as e:
        logger.error(f"Error fetching project: {e}")
        return None


@tool
def create_handoff(
    project_name: str,
    topic: str,
    context: Optional[str] = None,
    include_brain_dumps: bool = True
) -> str:
    """
    Create a handoff document for project ideation.
    
    Args:
        project_name: The project to create a handoff for
        topic: The topic/feature being discussed
        context: Additional context from the conversation
        include_brain_dumps: Whether to search for related brain dumps
    
    The handoff document will include:
    1. Current project state
    2. Related brain dumps (if any)
    3. Specific action items
    
    Take this document into the project's Cursor workspace
    to continue implementation.
    """
    timestamp = datetime.now()
    handoff_id = str(uuid4())
    
    # Get project info
    project = get_project_from_supabase(project_name)
    
    # Search for related brain dumps
    related_dumps = None
    if include_brain_dumps:
        try:
            supabase = get_supabase_client()
            if supabase:
                result = supabase.table("brain_dumps").select(
                    "id, title, content"
                ).ilike("content", f"%{topic}%").limit(3).execute()
                
                if result.data:
                    related_dumps = result.data
        except Exception as e:
            logger.error(f"Error searching brain dumps: {e}")
    
    # Build handoff content
    lines = [
        f"# Handoff: {topic}",
        "",
        f"**Project**: {project_name}",
        f"**Created**: {timestamp.strftime('%A, %B %d, %Y at %I:%M %p')}",
    ]
    
    if project and project.get("path"):
        lines.append(f"**Path**: `{project.get('path')}`")
    
    lines.extend([
        "",
        "---",
        "",
        "## Context",
        "",
    ])
    
    if context:
        lines.append(context)
    else:
        lines.append(f"*Ideating on: {topic}*")
    
    if related_dumps:
        lines.extend([
            "",
            "---",
            "",
            "## Related Brain Dumps",
            "",
        ])
        for dump in related_dumps:
            lines.append(f"- **{dump.get('title', 'Untitled')}**: {dump.get('content', '')[:100]}...")
    
    lines.extend([
        "",
        "---",
        "",
        "## Action Items",
        "",
        "- [ ] Review the context above",
        "- [ ] Determine if this fits in an existing PRD or needs a new one",
        "- [ ] If new PRD needed, create it with the next available number",
        "",
        "---",
        "",
        f"*Generated by Donna at {timestamp.strftime('%I:%M %p')}*",
    ])
    
    content = "\n".join(lines)
    
    # Save to Supabase
    try:
        supabase = get_supabase_client()
        if supabase:
            supabase.table("handoffs").insert({
                "id": handoff_id,
                "project_id": project.get("id") if project else project_name.lower(),
                "project_name": project.get("name") if project else project_name,
                "topic": topic,
                "content": content,
                "context": context,
                "related_brain_dumps": related_dumps,
                "created_at": timestamp.isoformat(),
            }).execute()
            logger.info(f"Handoff saved to Supabase: {handoff_id}")
    except Exception as e:
        logger.error(f"Failed to save handoff: {e}")
    
    project_path = project.get("path", "/path/to/project") if project else f"/path/to/{project_name}"
    
    return f"""✅ Handoff document created!

**Project**: {project_name}
**Topic**: {topic}
**ID**: `{handoff_id[:8]}...`

## Quick Actions

1. **Open in Cursor**: `cursor {project_path}`
2. **The handoff contains**:
   - Context for the feature
   - Related brain dumps
   - Action items

Take this into the project workspace to continue!

---

{content}
"""


@tool
def list_handoffs(project_name: Optional[str] = None, limit: int = 10) -> str:
    """
    List recent handoff documents.
    
    Args:
        project_name: Filter by project (optional)
        limit: Maximum number to return
    
    Returns list of handoff documents with dates and topics.
    """
    try:
        supabase = get_supabase_client()
        if not supabase:
            return "Database not connected."
        
        query = supabase.table("handoffs").select(
            "id, project_name, topic, created_at"
        ).order("created_at", desc=True).limit(limit)
        
        if project_name:
            query = query.ilike("project_name", f"%{project_name}%")
        
        result = query.execute()
        
        if not result.data:
            return "No handoff documents found."
        
        lines = ["# Recent Handoffs\n"]
        
        for handoff in result.data:
            project = handoff.get("project_name", "Unknown")
            topic = handoff.get("topic", "Untitled")
            created = handoff.get("created_at", "")[:10]
            
            lines.append(f"- **{topic}** ({project})")
            lines.append(f"  Date: {created}")
            lines.append("")
        
        return "\n".join(lines)
        
    except Exception as e:
        logger.error(f"Error listing handoffs: {e}")
        return f"Error: {str(e)}"


@tool
def get_handoff_content(handoff_id: str) -> str:
    """
    Read the content of a handoff document.
    
    Args:
        handoff_id: ID of the handoff (or partial ID)
    
    Returns the full content of the handoff.
    """
    try:
        supabase = get_supabase_client()
        if not supabase:
            return "Database not connected."
        
        result = supabase.table("handoffs").select("*").ilike(
            "id", f"{handoff_id}%"
        ).limit(1).execute()
        
        if not result.data:
            return f"Handoff not found with ID: {handoff_id}"
        
        handoff = result.data[0]
        return handoff.get("content", "No content available")
        
    except Exception as e:
        logger.error(f"Error getting handoff: {e}")
        return f"Error: {str(e)}"
