"""
Handoff document generation tools for Donna.

Creates context documents when ideating on specific projects,
allowing seamless transition from Donna to project workspaces.
"""

import json
import re
from pathlib import Path
from typing import Optional
from datetime import datetime

from langchain_core.tools import tool
from langchain_openai import ChatOpenAI

from donna.config import get_settings, get_handoffs_path
from donna.tools.projects import load_project_registry, get_project_prd_status
from donna.tools.brain_dump import search_brain_dumps


def ensure_handoff_directory(project_id: str) -> Path:
    """Ensure the handoff directory exists for a project."""
    handoffs_path = get_handoffs_path()
    project_path = handoffs_path / project_id
    project_path.mkdir(parents=True, exist_ok=True)
    return project_path


@tool
def create_handoff(
    project_name: str,
    topic: str,
    context: Optional[str] = None,
    include_brain_dumps: bool = True
) -> str:
    """
    Create a handoff document for project ideation.
    
    Args:
        project_name: The project to create a handoff for
        topic: The topic/feature being discussed
        context: Additional context from the conversation
        include_brain_dumps: Whether to search for related brain dumps
    
    The handoff document will include:
    1. Current project state (from .prd-status.json)
    2. Current PRD being worked on
    3. Next PRD in queue
    4. Related brain dumps (if any)
    5. Specific action items
    
    Take this document into the project's Cursor workspace
    to continue implementation.
    """
    registry = load_project_registry()
    
    # Find the project
    project = None
    for p in registry.projects:
        if p.id.lower() == project_name.lower() or p.name.lower() == project_name.lower():
            project = p
            break
    
    if not project:
        return f"Project '{project_name}' not found. Available: {', '.join(p.name for p in registry.projects)}"
    
    timestamp = datetime.now()
    
    # Generate slug for filename
    slug = re.sub(r'[^a-z0-9]+', '-', topic.lower()).strip('-')[:50]
    
    # Create handoff directory and file path
    handoff_dir = ensure_handoff_directory(project.id)
    filename = f"{timestamp.strftime('%Y-%m-%d')}_{slug}.md"
    file_path = handoff_dir / filename
    
    # Get PRD status
    prd_status = ""
    if project.prd_status_path and project.path:
        prd_status = get_project_prd_status.invoke({"project_name": project.name})
    
    # Search for related brain dumps
    related_dumps = ""
    if include_brain_dumps:
        dumps_result = search_brain_dumps.invoke({"query": topic, "limit": 3})
        if "found" in dumps_result.lower() or "##" in dumps_result:
            related_dumps = dumps_result
    
    # Build handoff content
    lines = [
        f"# Handoff: {topic}",
        "",
        f"**Project**: {project.name}",
        f"**Created**: {timestamp.strftime('%A, %B %d, %Y at %I:%M %p')}",
        f"**Path**: `{project.path}`",
        "",
        "---",
        "",
        "## Project State",
        "",
    ]
    
    if prd_status:
        lines.append(prd_status)
    else:
        lines.append("*No PRD status available*")
    
    lines.extend([
        "",
        "---",
        "",
        "## Context",
        "",
    ])
    
    if context:
        lines.append(context)
    else:
        lines.append(f"*Ideating on: {topic}*")
    
    if related_dumps:
        lines.extend([
            "",
            "---",
            "",
            "## Related Brain Dumps",
            "",
            related_dumps,
        ])
    
    lines.extend([
        "",
        "---",
        "",
        "## Action Items",
        "",
        "- [ ] Review the current PRD status above",
        "- [ ] Determine if this fits in an existing PRD or needs a new one",
        "- [ ] If new PRD needed, create it with the next available number",
        f"- [ ] Update `.prd-status.json` in `{project.prd_status_path or 'docs/prds/'}`",
        "",
        "---",
        "",
        "## Next Steps",
        "",
        "1. Open the project in Cursor:",
        f"   ```bash",
        f"   cursor {project.path}",
        f"   ```",
        "",
        "2. Review this handoff document",
        "",
        "3. Start implementing based on the PRD",
        "",
        "---",
        "",
        f"*Generated by Donna at {timestamp.strftime('%I:%M %p')}*",
    ])
    
    # Write file
    content = "\n".join(lines)
    with open(file_path, "w") as f:
        f.write(content)
    
    return f"""✅ Handoff document created!

**Project**: {project.name}
**Topic**: {topic}
**File**: `{file_path}`

## Quick Actions

1. **Open in Cursor**: `cursor {project.path}`
2. **View handoff**: The document contains:
   - Current PRD status
   - Related brain dumps
   - Action items

Take this into the project workspace to continue!
"""


@tool
def list_handoffs(project_name: Optional[str] = None, limit: int = 10) -> str:
    """
    List recent handoff documents.
    
    Args:
        project_name: Filter by project (optional)
        limit: Maximum number to return
    
    Returns list of handoff documents with dates and topics.
    """
    handoffs_path = get_handoffs_path()
    
    if not handoffs_path.exists():
        return "No handoffs created yet. Use `/handoff [project]` to create one."
    
    all_handoffs = []
    
    if project_name:
        # Single project
        project_dir = handoffs_path / project_name.lower()
        if project_dir.exists():
            all_handoffs = list(project_dir.glob("*.md"))
    else:
        # All projects
        all_handoffs = list(handoffs_path.rglob("*.md"))
    
    if not all_handoffs:
        return "No handoff documents found."
    
    # Sort by modification time (newest first)
    all_handoffs.sort(key=lambda f: f.stat().st_mtime, reverse=True)
    all_handoffs = all_handoffs[:limit]
    
    lines = ["# Recent Handoffs\n"]
    
    for handoff in all_handoffs:
        project = handoff.parent.name
        date_part = handoff.stem.split('_')[0] if '_' in handoff.stem else "Unknown"
        topic = handoff.stem.split('_', 1)[1] if '_' in handoff.stem else handoff.stem
        topic = topic.replace('-', ' ').title()
        
        lines.append(f"- **{topic}** ({project})")
        lines.append(f"  Date: {date_part}")
        lines.append(f"  File: `{handoff}`")
        lines.append("")
    
    return "\n".join(lines)


@tool
def get_handoff_content(file_path: str) -> str:
    """
    Read the content of a handoff document.
    
    Args:
        file_path: Path to the handoff file
    
    Returns the full content of the handoff.
    """
    path = Path(file_path)
    
    if not path.exists():
        return f"Handoff not found: {file_path}"
    
    with open(path, "r") as f:
        return f.read()


